theme: hacker
plugins: 
- jekyll-remote-theme
title: Adrian Mak
description: Scientist, Engineer, Swimmer, Musician, Father
header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: About  # <-- about.md

