remote_theme: eliottvincent/bay
header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: About  # <-- about.md
title: Adrian Mak
description: Scientist, Engineer, Swimmer, Musician, Father
