remote_theme: poole/poole
title: Adrian Mak
description: Scientist, Engineer, Swimmer, Musician, Father
header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: About  # <-- about.md

